### ISSUE TITLE
ビルドエラーが発生する

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-front#487]
main ブランチで `yarn build` したら以下のようなログが出されビルドが失敗します。

```bash
twinte-front $ yarn build
yarn run v1.22.11
$ yarn typecheck && vite build
$ vue-tsc --noEmit
vite v2.1.4 building for production...
transforming (71) node_modules/@sentry/utils/esm/dsn.js
warn - The `conservative` purge mode will be removed in Tailwind 2.0.
warn - Please switch to the new `layers` mode instead.
transforming (125) node_modules/@gtm-support/core/lib/assert-is-gtm-id.js(node:1221) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/hosokawa/projects/twinte/twinte-front/src/scss/main.scss'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at rebaseUrls (/home/hosokawa/projects/twinte/twinte-front/node_modules/vite/dist/node/chunks/dep-6e02b235.js:19170:33)
    at /home/hosokawa/projects/twinte/twinte-front/node_modules/vite/dist/node/chunks/dep-6e02b235.js:19120:21
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1221) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1221) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
transforming (417) src/styles/_index.scssUnexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(vite:css) transform "/home/hosokawa/projects/twinte/twinte-front/src/pages/404.vue?vue&type=style&index=0&scoped=true&lang.scss"
error during build:
Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(vite:css) transform "/home/hosokawa/projects/twinte/twinte-front/src/pages/404.vue?vue&type=style&index=0&scoped=true&lang.scss"
    at process.handleEmptyEventLoop (/home/hosokawa/projects/twinte/twinte-front/node_modules/rollup/dist/shared/rollup.js:23072:20)
    at Object.onceWrapper (events.js:520:26)
    at process.emit (events.js:400:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by HikaruEgashira** [comment]
リベース忘れてた（）
